In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [3]:
import numpy as np
import matplotlib.pyplot as plt

In [4]:
with open("poems.txt", "r", encoding="utf8") as f:
    text = f.read()

In [5]:
type(text)

str

In [12]:
text[:1200]

'प्रकृतिको झापट\n - इन्दिरा चापागाईं\nहिजाे मान्छे\nसबथाेक छाेडेर पैसाकाे लागि दाैडिन्थ्याे\nकर्म, कुकर्म जे सुकै गरी पैसा थुपार्थ्र्याे\nउसलाई लाग्थ्याे कि पैसा भए पछि सबथाेक हुन्छ\nन त साेचेकाे थियाे बहत्तर बैशाख बाह्रकाे भुकम्प आउंछ भनेर\nन त परिकल्पना गरेकाे थियाे काेराेनाले विश्व महामारी ल्याउँछ भनेर\nतर, आज मान्छे\nपैसाले जीवन किन्न सक्दाेरहेनछ भन्ने बिस्तारै बुझ्दैछ\nप्रकृतिकाे हिसाब किताब पैसाद्वारा हुँदाेरहेनछ भन्ने सुझ्दैछ\nभूकम्पले समानता ल्याएकाे थियाे धनि गरिव दुवैलाइ पालमुनि सुताएर\nकाेराेनाले थप पाठ पढाइरहेछ \nधनी गरिब दुवैलाइ एकसमान मृत्यू दिएर\nमृत्यूलाइ जित्न सकिदैन या जुनसुकै बेला जीवन किन्न सकिदैन भनेर\nत्यसैले त मान्छे आाज फेरि एकपटक "मानवता" फलाक्न थालेकाे छ\nअरुबेला विश्वासै नलाग्ने "भगवान" हरपल मनमनै अलाप्न थालेकाे छ\nमृत्यूकाे त्रासले छाेपे पछि भाइचाराकाे पाठ पढ्न थालेकाे छ\nअहमताकाे पर्दा हटाएर सबैकाे अस्तित्व हेर्न थालेकाे छ\n"बहुजन हिताय बहुजन सुखाय"काे सानाे दीप हृदयमा बालेकाे छ\nआफनाे मृत्यू धेरै टाढा छैन भन्ने कुरा मस्तिष्कमा राख्न थालेकाे छ\nमान्छेलाई अब

In [13]:
print(text[:1200])

प्रकृतिको झापट
 - इन्दिरा चापागाईं
हिजाे मान्छे
सबथाेक छाेडेर पैसाकाे लागि दाैडिन्थ्याे
कर्म, कुकर्म जे सुकै गरी पैसा थुपार्थ्र्याे
उसलाई लाग्थ्याे कि पैसा भए पछि सबथाेक हुन्छ
न त साेचेकाे थियाे बहत्तर बैशाख बाह्रकाे भुकम्प आउंछ भनेर
न त परिकल्पना गरेकाे थियाे काेराेनाले विश्व महामारी ल्याउँछ भनेर
तर, आज मान्छे
पैसाले जीवन किन्न सक्दाेरहेनछ भन्ने बिस्तारै बुझ्दैछ
प्रकृतिकाे हिसाब किताब पैसाद्वारा हुँदाेरहेनछ भन्ने सुझ्दैछ
भूकम्पले समानता ल्याएकाे थियाे धनि गरिव दुवैलाइ पालमुनि सुताएर
काेराेनाले थप पाठ पढाइरहेछ 
धनी गरिब दुवैलाइ एकसमान मृत्यू दिएर
मृत्यूलाइ जित्न सकिदैन या जुनसुकै बेला जीवन किन्न सकिदैन भनेर
त्यसैले त मान्छे आाज फेरि एकपटक "मानवता" फलाक्न थालेकाे छ
अरुबेला विश्वासै नलाग्ने "भगवान" हरपल मनमनै अलाप्न थालेकाे छ
मृत्यूकाे त्रासले छाेपे पछि भाइचाराकाे पाठ पढ्न थालेकाे छ
अहमताकाे पर्दा हटाएर सबैकाे अस्तित्व हेर्न थालेकाे छ
"बहुजन हिताय बहुजन सुखाय"काे सानाे दीप हृदयमा बालेकाे छ
आफनाे मृत्यू धेरै टाढा छैन भन्ने कुरा मस्तिष्कमा राख्न थालेकाे छ
मान्छेलाई अब थाेरै भए पनि "चेतना भ

In [14]:
len(text)

2054830

In [15]:
all_characters = set(text)

In [16]:
all_characters

{'\t',
 '\n',
 ' ',
 '!',
 '"',
 '#',
 '%',
 "'",
 '(',
 ')',
 '*',
 '+',
 ',',
 '-',
 '.',
 '/',
 '0',
 '1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 ':',
 ';',
 '=',
 '>',
 '?',
 '@',
 'A',
 'B',
 'C',
 'D',
 'E',
 'F',
 'H',
 'I',
 'K',
 'L',
 'M',
 'N',
 'O',
 'P',
 'R',
 'S',
 'T',
 'U',
 'V',
 'W',
 'X',
 '[',
 ']',
 '`',
 'a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 '|',
 '~',
 '\x81',
 '\x97',
 '\xa0',
 '¤',
 '¥',
 '¨',
 '«',
 '\xad',
 '°',
 '²',
 '´',
 '·',
 'º',
 'Ç',
 'Ó',
 'Ô',
 '×',
 'Þ',
 'è',
 'ó',
 '÷',
 'π',
 'ь',
 'ࣿ',
 'ँ',
 'ं',
 'ः',
 'अ',
 'आ',
 'इ',
 'ई',
 'उ',
 'ऊ',
 'ऋ',
 'ऎ',
 'ए',
 'ऐ',
 'ऑ',
 'ओ',
 'औ',
 'क',
 'ख',
 'ग',
 'घ',
 'ङ',
 'च',
 'छ',
 'ज',
 'झ',
 'ञ',
 'ट',
 'ठ',
 'ड',
 'ढ',
 'ण',
 'त',
 'थ',
 'द',
 'ध',
 'न',
 'ऩ',
 'प',
 'फ',
 'ब',
 'भ',
 'म',
 'य',
 'र',
 'ऱ',
 'ल',
 'ळ',
 'व',
 'श',
 'ष',
 'स',
 'ह',
 '़',
 'ऽ',
 'ा',
 'ि',
 'ी',
 'ु',
 '

In [17]:
len(all_characters)

225

In [18]:
# Decoder Num to letter

decoder = dict(enumerate(all_characters))

In [19]:
decoder

{0: '६',
 1: 'm',
 2: 'छ',
 3: '\uf0ae',
 4: 'u',
 5: '2',
 6: 'P',
 7: '☻',
 8: '\x97',
 9: 'त',
 10: '\u200d',
 11: 'A',
 12: 'फ़',
 13: '८',
 14: '\uf06c',
 15: '=',
 16: 'V',
 17: '~',
 18: 'W',
 19: 'ó',
 20: 'ऊ',
 21: "'",
 22: '"',
 23: 'I',
 24: 'ड',
 25: 'ड़',
 26: 'क',
 27: ')',
 28: '¤',
 29: 'ो',
 30: '7',
 31: '•',
 32: '\x81',
 33: '—',
 34: '‘',
 35: ':',
 36: '१',
 37: 'è',
 38: '−',
 39: '@',
 40: 'C',
 41: '॰',
 42: '―',
 43: 'ि',
 44: 'x',
 45: 'D',
 46: 'ऎ',
 47: '%',
 48: '–',
 49: 'ओ',
 50: 'ॅ',
 51: 'Ô',
 52: '☼',
 53: '4',
 54: 'य',
 55: '\uf04a',
 56: 'E',
 57: 'फ',
 58: 'ख',
 59: '*',
 60: 'r',
 61: '²',
 62: 'Ç',
 63: '४',
 64: 'ठ',
 65: 'g',
 66: '☯',
 67: 'ू',
 68: '/',
 69: 'ु',
 70: 'F',
 71: 'ः',
 72: 'i',
 73: '२',
 74: 'ढ',
 75: '5',
 76: '\u3000',
 77: 'ञ',
 78: '़',
 79: 'ल',
 80: 'ढ़',
 81: '\u200c',
 82: 'ॠ',
 83: 'द',
 84: '¥',
 85: 'े',
 86: 'न',
 87: '¨',
 88: '🌷',
 89: '\n',
 90: '1',
 91: 'R',
 92: 'o',
 93: '°',
 94: 'j',
 95: 'ग',
 96: 'c',
 97

In [22]:
# Encoder :  Letter to num

encoder = {v:k for k,v in decoder.items()}


In [23]:
encoder

{'६': 0,
 'm': 1,
 'छ': 2,
 '\uf0ae': 3,
 'u': 4,
 '2': 5,
 'P': 6,
 '☻': 7,
 '\x97': 8,
 'त': 9,
 '\u200d': 10,
 'A': 11,
 'फ़': 12,
 '८': 13,
 '\uf06c': 14,
 '=': 15,
 'V': 16,
 '~': 17,
 'W': 18,
 'ó': 19,
 'ऊ': 20,
 "'": 21,
 '"': 22,
 'I': 23,
 'ड': 24,
 'ड़': 25,
 'क': 26,
 ')': 27,
 '¤': 28,
 'ो': 29,
 '7': 30,
 '•': 31,
 '\x81': 32,
 '—': 33,
 '‘': 34,
 ':': 35,
 '१': 36,
 'è': 37,
 '−': 38,
 '@': 39,
 'C': 40,
 '॰': 41,
 '―': 42,
 'ि': 43,
 'x': 44,
 'D': 45,
 'ऎ': 46,
 '%': 47,
 '–': 48,
 'ओ': 49,
 'ॅ': 50,
 'Ô': 51,
 '☼': 52,
 '4': 53,
 'य': 54,
 '\uf04a': 55,
 'E': 56,
 'फ': 57,
 'ख': 58,
 '*': 59,
 'r': 60,
 '²': 61,
 'Ç': 62,
 '४': 63,
 'ठ': 64,
 'g': 65,
 '☯': 66,
 'ू': 67,
 '/': 68,
 'ु': 69,
 'F': 70,
 'ः': 71,
 'i': 72,
 '२': 73,
 'ढ': 74,
 '5': 75,
 '\u3000': 76,
 'ञ': 77,
 '़': 78,
 'ल': 79,
 'ढ़': 80,
 '\u200c': 81,
 'ॠ': 82,
 'द': 83,
 '¥': 84,
 'े': 85,
 'न': 86,
 '¨': 87,
 '🌷': 88,
 '\n': 89,
 '1': 90,
 'R': 91,
 'o': 92,
 '°': 93,
 'j': 94,
 'ग': 95,
 'c': 96,
 '०

In [27]:
encoded_text = np.array([encoder[char] for char in text])

In [28]:
encoded_text[:100]

array([136, 134, 107,  26, 101,   9,  43,  26,  29, 109, 153, 221, 136,
       210,  89, 109, 105, 109, 163,  86, 134,  83,  43, 107, 221, 109,
       168, 221, 136, 221,  95, 221, 102, 222,  89, 128,  43, 200, 221,
        85, 109, 132, 221,  86, 134,   2,  85,  89, 205, 223, 194, 221,
        85,  26, 109,   2, 221,  85,  24,  85, 107, 109, 136, 196, 205,
       221,  26, 221,  85, 109,  79, 221,  95,  43, 109,  83, 221, 196,
        24,  43,  86, 134, 194, 134,  54, 221,  85,  89,  26, 107, 134,
       132, 213, 109,  26,  69,  26, 107, 134, 132])

In [41]:
# Create a one hot encoder

def one_hot_encoder(encoded_text, num_uni_characters):
    
    
    # encoded_text --> batch of encoded text
    # num_uni_characters --> len(set(text))
    
    one_hot = np.zeros((encoded_text.size, num_uni_characters))
    one_hot = one_hot.astype(np.float32)
    one_hot[np.arange(one_hot.shape[0]), encoded_text.flatten()] = 1.0
    one_hot = one_hot.reshape((*encoded_text.shape, num_uni_characters))
    return one_hot

In [42]:
arr = np.array([1,2,0,1,2])

In [43]:
one_hot_encoder(arr, 3)

array([[0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)

# Generate Training Datasets

In [51]:
example_text = np.arange(12)

In [52]:
example_text

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [54]:
example_text.reshape(4,-1)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [55]:
def generate_batches(encoded_text, samp_per_batch=10, seq_len=50):
    
    '''
    Generate (using yield) batches for training.
    
    X: Encoded Text of length seq_len
    Y: Encoded Text shifted by one
    
    Example:
    
    X:
    
    [[1 2 3]]
    
    Y:
    
    [[ 2 3 4]]
    
    encoded_text : Complete Encoded Text to make batches from
    batch_size : Number of samples per batch
    seq_len : Length of character sequence
       
    '''
    # Total number of characters per batch
    # Example: If samp_per_batch is 2 and seq_len is 50, then 100
    # characters come out per batch.
    char_per_batch = samp_per_batch * seq_len
    
    # Number of batches available to make
    # Use int() to roun to nearest integer
    num_batches_avail = int(len(encoded_text)/char_per_batch)
    
    # Cut off end of encoded_text that
    # won't fit evenly into a batch
    encoded_text = encoded_text[:num_batches_avail * char_per_batch]
    
    
    # Reshape text into rows the size of a batch
    encoded_text = encoded_text.reshape((samp_per_batch, -1))
    

    # Go through each row in array.
    for n in range(0, encoded_text.shape[1], seq_len):
        
        # Grab feature characters
        x = encoded_text[:, n:n+seq_len]
        
        # y is the target shifted over by 1
        y = np.zeros_like(x)
       
        #
        try:
            y[:, :-1] = x[:, 1:]
            y[:, -1]  = encoded_text[:, n+seq_len]
            
        # FOR POTENTIAL INDEXING ERROR AT THE END    
        except:
            y[:, :-1] = x[:, 1:]
            y[:, -1] = encoded_text[:, 0]
            
        yield x, y

# LSTM Model

In [56]:
class CharModel(nn.Module):
    
    def __init__(self, all_chars, num_hidden=256, num_layers=4, dropout_porbability=0.5, use_gpu=False):
        super().__init__()
        
        self.dropout_porbability = dropout_porbability
        self.num_layers = num_layers
        self.num_hidden = num_hidden
        self.use_gpu = use_gpu
        
        self.all_chars = all_chars
        self.decoder = dict(enumerate(all_chars))
        self.encoder = {char:ind for ind, char in decoder.items()}
        
        self.lstm = nn.LSTM(
            len(self.all_chars),
            num_hidden,
            num_layers,
            dropout=dropout_porbability,
            batch_first=True
        )
        
        self.dropout = nn.Dropout(dropout_porbability)
        
        self.fc_linear = nn.Linear(num_hidden, len(self.all_chars))
    
    
    def forward(self,x,hidden):
        
        lstm_output, hidden = self.lstm(x, hidden)
        
        drop_output = self.dropout(lstm_output)
        
        
        drop_output = drop_output.contiguous().view(-1, self.num_hidden)
        
        final_out = self.fc_linear(drop_output)
        
        return final_out, hidden
    
    def hidden_state(self, batch_size):
        if self.use_gpu:
            hidden = (
                torch.zeros(self.num_layers, batch_size, self.num_hidden).cuda(),
                torch.zeros(self.num_layers, batch_size, self.num_hidden).cuda()
            )
        else:
            hidden = (
                torch.zeros(self.num_layers, batch_size, self.num_hidden),
                torch.zeros(self.num_layers, batch_size, self.num_hidden)
            )
            
        return hidden

In [57]:
model = CharModel(
    all_chars=all_characters,
    num_hidden=512,
    num_layers=3,
    dropout_porbability=0.5,
    use_gpu=False
)

In [58]:
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)
criterion = nn.CrossEntropyLoss()

In [59]:
train_percent = 0.9

In [60]:
train_ind = int(len(encoded_text)*train_percent)

In [61]:
train_data = encoded_text[:train_ind]

In [62]:
val_data = encoded_text[train_ind:]

In [63]:
len(train_data)

1849347

In [64]:
len(val_data)

205483

# Training the model

In [67]:
# variables
epochs = 1
batch_size = 100

seq_len = 100

tracker = 0

num_char = max(encoded_text)+1

In [68]:
# Set model to train
model.train()


# Check to see if using GPU
if model.use_gpu:
    model.cuda()

for i in range(epochs):
    
    hidden = model.hidden_state(batch_size)
    
    
    for x,y in generate_batches(train_data,batch_size,seq_len):
        
        tracker += 1
        
        # One Hot Encode incoming data
        x = one_hot_encoder(x,num_char)
        
        # Convert Numpy Arrays to Tensor
        
        inputs = torch.from_numpy(x)
        targets = torch.from_numpy(y)
        
        # Adjust for GPU if necessary
        
        if model.use_gpu:
            
            inputs = inputs.cuda()
            targets = targets.cuda()
            
        # Reset Hidden State
        # If we dont' reset we would backpropagate through all training history
        hidden = tuple([state.data for state in hidden])
        
        model.zero_grad()
        
        lstm_output, hidden = model.forward(inputs,hidden)
        loss = criterion(lstm_output,targets.view(batch_size*seq_len).long())
        
        loss.backward()
        
        # POSSIBLE EXPLODING GRADIENT PROBLEM!
        # LET"S CLIP JUST IN CASE
        nn.utils.clip_grad_norm_(model.parameters(),max_norm=5)
        
        optimizer.step()
        
        
        
        ###################################
        ### CHECK ON VALIDATION SET ######
        #################################
        
        if tracker % 25 == 0:
            
            val_hidden = model.hidden_state(batch_size)
            val_losses = []
            model.eval()
            
            for x,y in generate_batches(val_data,batch_size,seq_len):
                
                # One Hot Encode incoming data
                x = one_hot_encoder(x,num_char)
                

                # Convert Numpy Arrays to Tensor

                inputs = torch.from_numpy(x)
                targets = torch.from_numpy(y)

                # Adjust for GPU if necessary

                if model.use_gpu:

                    inputs = inputs.cuda()
                    targets = targets.cuda()
                    
                # Reset Hidden State
                # If we dont' reset we would backpropagate through 
                # all training history
                val_hidden = tuple([state.data for state in val_hidden])
                
                lstm_output, val_hidden = model.forward(inputs,val_hidden)
                val_loss = criterion(lstm_output,targets.view(batch_size*seq_len).long())
        
                val_losses.append(val_loss.item())
            
            # Reset to training model after val for loop
            model.train()
            
            print(f"Epoch: {i} Step: {tracker} Val Loss: {val_loss.item()}")

Epoch: 0 Step: 25 Val Loss: 3.4744036197662354


KeyboardInterrupt: 

In [69]:
model_name = 'nepali_poem.net'
torch.save(model.state_dict(),model_name)

# Loading the model

In [70]:
# MUST MATCH THE EXACT SAME SETTINGS AS MODEL USED DURING TRAINING!

model = CharModel(
    all_chars=all_characters,
    num_hidden=512,
    num_layers=3,
    dropout_porbability=0.5,
    use_gpu=False,
)

model.load_state_dict(torch.load(model_name))
model.eval()

CharModel(
  (lstm): LSTM(225, 512, num_layers=3, batch_first=True, dropout=0.5)
  (dropout): Dropout(p=0.5, inplace=False)
  (fc_linear): Linear(in_features=512, out_features=225, bias=True)
)

# Predicting the text

In [71]:
def predict_next_char(model, char, hidden=None, k=1):
    
    encoded_text = model.encoder[char]
    
    encoded_text = np.array([[encoded_text]])
    
    encoded_text = one_hot_encoder(encoded_text, len(model.all_chars))
    
    inputs = torch.from_numpy(encoded_text)
    
    if model.use_gpu:
        inputs = inputs.cuda()
    
    hidden = tuple([state.data for state in hidden])
    
    lstm_out , hidden = model(inputs, hidden)
    
    probs = F.softmax(lstm_out, dim=1).data
    
    if model.use_gpu:
        probs = probs.cpu()
        
    probs, index_positions = probs.topk(k)
    
    index_positions = index_positions.numpy().squeeze()
    
    probs = probs.numpy().flatten()
    
    probs = probs/probs.sum()
    
    char = np.random.choice(index_positions, p=probs)
    
    return model.decoder[char], hidden

In [72]:
def generate_text(model, size, seed="The", k=1):
    
    if model.use_gpu:
        model.cuda()
    else:
        model.cpu()
        
    model.eval()
    
    output_chars = [c for c in seed]
    
    hidden = model.hidden_state(1)
    
    for char in seed:
        char, hidden = predict_next_char(model, char, hidden, k=k)
    
    output_chars.append(char)
    
    for i in range(size):
        char, hidden = predict_next_char(model, output_chars[-1], hidden, k=k)
        
        output_chars.append(char)
    
    
    return ''.join(output_chars)

In [73]:
print(generate_text(model, 1000, seed = "मेरो ", k=3))

मेरो ा ा ्     ा    ा ा्  ा्् ा  ्ाा     ् ा  ा ा््    ्  ा ्््  ा ्ाा् ्ा  ााा  ाा ्ा्ा  ्   ा््ा्ा्  ााा ््ाा  ्  ा् ा     ्् ा   ा्  ाा    ्ा्ाााा  ाा्   ा ा     ा््ा  ् ााा्   ा ्         ्ा  ा्् ्  ाा  ाा ्ा ा ाा् ा  ा ा््  ा ्ा  ्ाा ा्      ा    ाा ा ्ाााा  ्ाा्ा   ाा  ा ्ा्ा ााा  ्ाा  ्ा ा ा््  ् ाााा ्् ्ा    ा          ् ््् ााा ्ाा  ा् ा   ्     ाा ्  ् ाा   ््  ््  ाा ्ााा् ््   ्ा ाा ा ्ाा   ा् ा ा्  ्ा ्ााा ् ्ा्् ा   ् ाा्््  ा ाा ् ाा ा्  ाा  ा  ा    ्   ्  ाा्ाा   ्  ा    ा    ाा ा्   ्  ् ा    ््ा ा    ाा्  ् ् ा ा् ्    ा ाा ााा् ्ाा् ा ा  ्ा  ््ााा   ्ा् ्ाा  ाा  ा् ्ााा ा    ्ा ा् ा  ्  ा  ा्ाााा् ा् ्  ा्   ा      ा््ा ा्  ््् ा ा ा     ्ा      ््   ा््  ्  ा  ्  ा ् ् ा ्् ््         ा्  ा       ाा  ा्् ्  ा  ा  ्ा्  ्  ्   ाा  ा ााा     ् ्ाााा्  ् ा््ा  ्ा       ् ा    ्ा््ा     ्ााा् ा ्ाा ् ा     ा ्ा  ा््    ा  ्  ा ् ् ा ््ा्    ्ा    ा    ा  ्ा ्ााा्    ्ा ा  ााा््् ा   ््  ्    ्  ्  ा्ा्    ा  ्ाा ्््   ्ा ा     ाा    ा््ा  ााा्ा  ा्  ्ा्   ्् ् ् ््््््ा